-- Rimozione colonne ponteggi legacy dalla tabella opportunities (non usate da GDM Lattonerie)
ALTER TABLE opportunities
  DROP COLUMN IF EXISTS transpallet,
  DROP COLUMN IF EXISTS posiz_camion,
  DROP COLUMN IF EXISTS puo_scaricare,
  DROP COLUMN IF EXISTS luogo_scarico,
  DROP COLUMN IF EXISTS ritiro_esubero,
  DROP COLUMN IF EXISTS cartelli_stradali,
  DROP COLUMN IF EXISTS permessi_viabilita,
  DROP COLUMN IF EXISTS permesso_sosta,
  DROP COLUMN IF EXISTS ponteggio_per,
  DROP COLUMN IF EXISTS gru_cantiere,
  DROP COLUMN IF EXISTS luci_segnalazione,
  DROP COLUMN IF EXISTS a_carico_cliente,
  DROP COLUMN IF EXISTS orari_lavoro,
  DROP COLUMN IF EXISTS ancoraggi,
  DROP COLUMN IF EXISTS ponteggio_per_altro_note,
  DROP COLUMN IF EXISTS a_carico_cliente_altro_note,
  DROP COLUMN IF EXISTS ancoraggi_altro_note,
  DROP COLUMN IF EXISTS maestranze,
  DROP COLUMN IF EXISTS montacarichi;
