-- Rimozione tabelle legacy PROXIT, SAL, PROGETTI e relativi moduli disabilitati
DROP TABLE IF EXISTS daily_assignments CASCADE;
DROP TABLE IF EXISTS warehouse_balances CASCADE;
DROP TABLE IF EXISTS team_members CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS drivers CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS workers CASCADE;
DROP TABLE IF EXISTS proxit_presence CASCADE;
DROP TABLE IF EXISTS project_tasks CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS project_stages CASCADE;
DROP TABLE IF EXISTS sal_voci CASCADE;
DROP TABLE IF EXISTS sal_periods CASCADE;
DROP TABLE IF EXISTS external_engineers CASCADE;
